version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Installing dependencies...
  pre_build:
    commands:
      - echo Running pre-build steps...
      - echo "123456666" > in_build
  build:
    commands:
      - echo Building the application...
  post_build:
    commands:
      - echo Running post-build steps...

artifacts:
  files:
    - "**/*"
  discard-paths: no 

