version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo Installing dependencies...
      - echo "123" > in_build
  pre_build:
    commands:
      - echo Preparing environment...
  build:
    commands:
      - echo Building application...
  post_build:
    commands:
      - echo Build completed successfully!
artifacts:
  files:
    - '**/*'

